a = input('Digite algo: ')
print('O tipo primitivo desse valor é ',type(a))
print('Só tem espaço? ', a.isspace())
print('É um número? ', a.isnumeric())
print('É alfabetico? ', a.isalpha())
print('Tem letras e números? ', a.isalnum())
print('Está em maiúsculo? ', a.isupper())
print('Está em minúsculas? ', a.islower())
print('A letras maiúsculas e minúsculas? ', a.istitle())
